### ISSUE TITLE
Please elaborate what this does.

### ISSUE THREAD

**Issue by ax-hd** [isaacs/server-destroy#12]
Hey, I came across this npm module in the react-boilerplate repo. Can someone elaborate on what problem it solves and how it solves them and how things were done before this module. Just a brief explanation. Thank you.

**Comment by gunjpan** [comment]
@ax-hd  following stackoverflow question explains what this does:
https://stackoverflow.com/questions/14626636/how-do-i-shutdown-a-node-js-https-server-immediately

**Comment by gunjpan** [comment]
@isaacs ☝️ good to close?!

**Comment by isaacs** [comment]
In short: it lets you destroy a server and sever all open connections.  `server.close()` just stops accepting new connections, it doesn't destroy any existing open connections.
