### ISSUE TITLE
connection close event

### ISSUE THREAD

**Issue by fanatid** [isaacs/server-destroy#6]
@isaacs should not be used `once`, not `on` for connection close event? (for preventing memory leaks)
[line in code](https://github.com/isaacs/server-destroy/blob/13f04e499dac6e739fb8fb5fac8745cb083ef87e/index.js#L9)

**Comment by sarsamurmu** [comment]
It can't be `once`, because many clients can connect to a server. If we use `once`, the handler will be called only once, thus causing bugs.

**Comment by fanatid** [comment]
It's not about the server, it's about `close` event for one specified connection. After 4 years, I'm not sure why I opened this issue. It does not matter here, `on` or `once` -- both will work.
